steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/api-pinjol", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/api-pinjol"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "api-pinjol",
        "--image", "gcr.io/$PROJECT_ID/api-pinjol",
        "--timeout", "1000s",
        "--port", "3000",
        "--region", "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "DB_HOST=34.55.111.115,DB_USER=root,DB_PASS=,DB_NAME=pinjol_db,NIK_SECRET_KEY=$_NIK_SECRET_KEY,NIK_IV=$_NIK_IV",
        "--update-secrets",
        "GOOGLE_APPLICATION_CREDENTIALS=gcs-key:latest"
      ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _NIK_SECRET_KEY: "defaultSecretKeyIfAny"
  _NIK_IV: "defaultIVIfAny"
